##Evaluating Regression Models

##Author -Yashas Samaga




### libraries

In [1]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestRegressor

### Import Data Set

In [2]:
df = pd.read_csv("Data.csv")
print("Data")
print(df)

x= df.iloc[:,:-1].values
y=df.iloc[:,-1].values

print("Features")
print(x)

print("Dependent Variable")
print(y)

Data
         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]
Features
[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
Dependent Variable
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set


In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=1)


In [4]:
print("training set features")
print(len(x_train))
print("training set dependent variables")
print(len(y_train))

print("Test set features")
print(len(x_test))
print("Test set dependent variables")
print(len(y_test))

training set features
7654
training set dependent variables
7654
Test set features
1914
Test set dependent variables
1914


In [5]:
poly = PolynomialFeatures(degree=2)
print(x_train[0:5,:])
x_poly=poly.fit_transform(x_train)
print(x_poly[0:5,:])

[[   6.61   38.91 1015.77   92.31]
 [  22.72   65.61 1014.64   70.53]
 [  10.06   39.61 1018.22   70.22]
 [  27.53   67.83 1009.4    53.73]
 [  23.89   48.41 1010.48   62.31]]
[[1.00000000e+00 6.61000000e+00 3.89100000e+01 1.01577000e+03
  9.23100000e+01 4.36921000e+01 2.57195100e+02 6.71423970e+03
  6.10169100e+02 1.51398810e+03 3.95236107e+04 3.59178210e+03
  1.03178869e+06 9.37657287e+04 8.52113610e+03]
 [1.00000000e+00 2.27200000e+01 6.56100000e+01 1.01464000e+03
  7.05300000e+01 5.16198400e+02 1.49065920e+03 2.30526208e+04
  1.60244160e+03 4.30467210e+03 6.65705304e+04 4.62747330e+03
  1.02949433e+06 7.15625592e+04 4.97448090e+03]
 [1.00000000e+00 1.00600000e+01 3.96100000e+01 1.01822000e+03
  7.02200000e+01 1.01203600e+02 3.98476600e+02 1.02432932e+04
  7.06413200e+02 1.56895210e+03 4.03316942e+04 2.78141420e+03
  1.03677197e+06 7.14994084e+04 4.93084840e+03]
 [1.00000000e+00 2.75300000e+01 6.78300000e+01 1.00940000e+03
  5.37300000e+01 7.57900900e+02 1.86735990e+03 2.77887820e+0

In [6]:
def evalModel(y_test,y_pred):
  from sklearn.metrics import r2_score
  return r2_score(y_test, y_pred)

### Training Different Models

#### multipleRegression

In [7]:
def multipleRegression(x_train,y_train,x_test,y_test):
  print("multipleRegression ")

  regressor=linear_model.LinearRegression()
  regressor.fit(x_train,y_train)
  y_predict=regressor.predict(x_test)
  print(np.concatenate([y_test.reshape(-1,1),y_predict.reshape(-1,1)],axis=1))

  r2Score=evalModel(y_test=y_test,y_pred=y_predict)
  print("r2Score ")

  print(r2Score)
  return ("multipleRegression",r2Score)

#### polynomialRegression

In [8]:
def polynomialRegression(x_train,y_train,x_test,y_test):
  print("polynomialRegression ")

  poly = PolynomialFeatures(degree=4)
  x_train_poly=poly.fit_transform(x_train)
  regressor=linear_model.LinearRegression()
  regressor.fit(x_train_poly,y_train)

  y_predict=regressor.predict(poly.transform(x_test))
  print(np.concatenate([y_test.reshape(-1,1),y_predict.reshape(-1,1)],axis=1))

  r2Score=evalModel(y_test=y_test,y_pred=y_predict)
  print("r2Score ")

  print(r2Score)
  return ("polynomialRegression",r2Score)

#### supportVectorRegression

In [9]:
def supportVectorRegression(x_train,y_train,x_test,y_test):
  print("supportVectorRegression ")

  # feature scaling for features and dependent variables
  scaler_x = preprocessing.StandardScaler().fit(x_train)
  scaler_y = preprocessing.StandardScaler().fit(y_train.reshape(-1,1))

  x_scaled=scaler_x.transform(x_train)
  y_scaled=scaler_y.transform(y_train.reshape(-1,1))

  print("x_scaled")
  print(x_scaled)
  print("y_scaled")
  print(y_scaled)


  regr = svm.SVR()
  regr.fit(x_scaled,y_scaled)

  y_predict= scaler_y.inverse_transform(regr.predict(scaler_x.transform(x_test)).reshape(-1,1))
  print(np.concatenate([y_test.reshape(-1,1),y_predict.reshape(-1,1)],axis=1))


  r2Score=evalModel(y_test=y_test,y_pred=y_predict)
  print("r2Score ")

  print(r2Score)
  return ("supportVectorRegression",r2Score)


#### decisionTreeRegression

In [10]:
def decisionTreeRegression(x_train,y_train,x_test,y_test):
  print("decisionTreeRegression ")

  regressor=tree.DecisionTreeRegressor()
  regressor.fit(x_train,y_train)

  y_predict=regressor.predict(x_test)
  print(np.concatenate([y_test.reshape(-1,1),y_predict.reshape(-1,1)],axis=1))

  r2Score=evalModel(y_test=y_test,y_pred=y_predict)
  print("r2Score ")

  print(r2Score)
  return ("decisionTreeRegression",r2Score)

#### randomForestsRegression

In [11]:
def randomForestsRegression(x_train,y_train,x_test,y_test):
  print("randomForestsRegression ")

  regressor= RandomForestRegressor(n_estimators=100)
  regressor.fit(x_train,y_train)

  y_predict=regressor.predict(x_test)
  print(np.concatenate([y_test.reshape(-1,1),y_predict.reshape(-1,1)],axis=1))


  r2Score=evalModel(y_test=y_test,y_pred=y_predict)
  print("r2Score ")

  print(r2Score)
  return ("randomForestsRegression",r2Score)

In [12]:
regressionModels = [multipleRegression , polynomialRegression, supportVectorRegression, decisionTreeRegression , randomForestsRegression]

### Finding the Best Model

In [13]:
def findBestPerformingRegressionModel():
  bestPerforming = []
  for func in regressionModels:
    print("-----------------------")
    result=func(x_train,y_train,x_test,y_test)
    modelName, score = result

    if(not bestPerforming):
      bestPerforming= [modelName,score]
    elif(score > bestPerforming[1]):
      bestPerforming= [modelName,score]

    print("-----------------------")

  return bestPerforming


In [14]:
result= findBestPerformingRegressionModel()

-----------------------
multipleRegression 
[[458.96       457.25522108]
 [463.29       466.71927366]
 [435.27       440.36694911]
 ...
 [476.22       476.40502919]
 [440.29       424.61609708]
 [467.92       463.91141143]]
r2Score 
0.9321860060402447
-----------------------
-----------------------
polynomialRegression 
[[458.96       456.53715034]
 [463.29       462.81675689]
 [435.27       438.39829603]
 ...
 [476.22       476.43032753]
 [440.29       432.52720104]
 [467.92       464.47742364]]
r2Score 
0.9446187158746087
-----------------------
-----------------------
supportVectorRegression 
x_scaled
[[-1.75440309 -1.21216858  0.42112637  1.3027435 ]
 [ 0.41388954  0.88854693  0.23226259 -0.1942825 ]
 [-1.29005737 -1.15709364  0.83060976 -0.21559003]
 ...
 [-0.1419794  -1.16260113 -0.78392477 -0.32625174]
 [ 0.44619185 -0.73222983 -0.17387808 -1.54971652]
 [ 0.11509316 -0.36401453 -0.61010325 -0.17503699]]
y_scaled
[[ 1.76193974]
 [-0.31293594]
 [ 1.02914634]
 ...
 [ 0.48219782]
 [

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[458.96       456.98286871]
 [463.29       463.66609133]
 [435.27       437.52351516]
 ...
 [476.22       476.32503421]
 [440.29       432.91249439]
 [467.92       464.26056348]]
r2Score 
0.9479978713795594
-----------------------
-----------------------
decisionTreeRegression 
[[458.96 459.65]
 [463.29 462.26]
 [435.27 436.03]
 ...
 [476.22 473.77]
 [440.29 432.78]
 [467.92 468.14]]
r2Score 
0.9321167717577502
-----------------------
-----------------------
randomForestsRegression 
[[458.96   457.1747]
 [463.29   463.931 ]
 [435.27   438.5261]
 ...
 [476.22   476.0145]
 [440.29   433.7622]
 [467.92   465.3843]]
r2Score 
0.9674423514936644
-----------------------


In [15]:
result

['randomForestsRegression', 0.9674423514936644]