##Multiple linear Regression

##Author -Yashas Samaga




### libraries

In [29]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt

### Import Data Set

In [30]:
df = pd.read_csv("50_Startups.csv")
print("Data")
print(df)

x= df.iloc[:,:-1].values
y=df.iloc[:,-1].values

print("Features")

print(x)

print("Dependent Variable")

print(y)

Data
    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39  

###Encoding the Independent Variable

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
type(x)

numpy.ndarray

In [32]:
ct.get_feature_names_out()

array(['encoder__x3_California', 'encoder__x3_Florida',
       'encoder__x3_New York', 'remainder__x0', 'remainder__x1',
       'remainder__x2'], dtype=object)

No need to worry about the dummy varoable trap - the library manages it

In [33]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

### Splitting the dataset into the Training set and Test set


In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=1)


### Training multiple linear regression model on the training set

In [35]:
print("training set features")

print(X_train)
print("training set dependent variables")
print(y_train)

training set features
[[1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 28663.76 127056.21 201126.82]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 77044.01 99281.34 140574.81]
 [0.0 1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 22177.74 154806.14 28334.72]
 [1.0 0.0 0.0 46426.07 157693.92 2

In [36]:
from sklearn import linear_model
regressor=linear_model.LinearRegression()
regressor.fit(X_train,y_train)
# fit methd trains the model on the training set

LinearRegression()

###Predicting Test Set resukts

In [37]:
print("Test Set features")
print(X_test)
print("Test Set Dependent variable")
print(y_test)

y_predict=regressor.predict(X_test)

Test Set features
[[0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]]
Test Set Dependent variable
[105008.31  96479.51  78239.91  81229.06 191050.39 182901.99  35673.41
 101004.64  49490.75  97483.56]


In [38]:
y_predict

array([114664.41715867,  90593.15531621,  75692.84151574,  70221.88679652,
       179790.25514872, 171576.92018521,  49753.5875203 , 102276.65888936,
        58649.37795761,  98272.02561131])

###Comparing Test vs predicted profits

In [39]:
comparison = np.concatenate( ( y_test.reshape(-1,1 ) ,y_predict.reshape(-1,1) ), axis=1)

In [40]:
comparison

array([[105008.31      , 114664.41715867],
       [ 96479.51      ,  90593.15531621],
       [ 78239.91      ,  75692.84151574],
       [ 81229.06      ,  70221.88679652],
       [191050.39      , 179790.25514872],
       [182901.99      , 171576.92018521],
       [ 35673.41      ,  49753.5875203 ],
       [101004.64      , 102276.65888936],
       [ 49490.75      ,  58649.37795761],
       [ 97483.56      ,  98272.02561131]])

aeb=a×10

In [41]:
print("Slope:", regressor.coef_)
print("Intercept:", regressor.intercept_)

Slope: [-2.85177769e+02  2.97560876e+02 -1.23831070e+01  7.74342081e-01
 -9.44369585e-03  2.89183133e-02]
Intercept: 49834.88507322592


## Making a single prediction ( example the profit of a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = 'California')

model was trained with this dummy variables in this order while oneHit Encoding
Make sure the order of features matches the training set feature  that the model was trained

In [42]:
ct.get_feature_names_out()

array(['encoder__x3_California', 'encoder__x3_Florida',
       'encoder__x3_New York', 'remainder__x0', 'remainder__x1',
       'remainder__x2'], dtype=object)

In [43]:
print(regressor.predict([[1,0,0,160000,130000,300000]]))

[180892.2538066]
