#Artificial Neural Network







#Author- Yashas Samaga

## imports

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from keras import layers

from sklearn.model_selection import train_test_split



In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


## Data Preprocessing

### importing  Datasets

In [3]:
df = pd.read_csv('Churn_Modelling.csv')
print(df.shape)
df


(10000, 14)


,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [4]:
x= df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [5]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y


array([1, 0, 1, ..., 1, 1, 0])

### Encoding Categorical Data

#### Label encoding of gender column

In [7]:
x[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])


In [9]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

#### One Hot encoding of Geography column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(ct.get_feature_names_out())

['encoder__x1_France' 'encoder__x1_Germany' 'encoder__x1_Spain'
 'remainder__x0' 'remainder__x2' 'remainder__x3' 'remainder__x4'
 'remainder__x5' 'remainder__x6' 'remainder__x7' 'remainder__x8'
 'remainder__x9']


In [11]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

#### Split data into training  and test sets

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=0)


In [13]:
x_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

#### Feature scaling

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train =scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [15]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## Building ANN

In [16]:
def displayNeuralNetwork(model):
  print(model.summary())
  print("----------------------------------")
  print(model.get_weights())

### initializing ANN

In [17]:
ann = keras.Sequential()


### Adding input layer and first Hidden Layer

In [18]:
len(x_train[0])

12

In [19]:
ann.add(keras.Input(shape=(len(x_train[0]),)))


In [20]:
ann.add(layers.Dense(units=6,activation="relu", name="deepLayer-1"))

In [21]:
displayNeuralNetwork(ann)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ deepLayer-1 (Dense)             │ (None, 6)              │            78 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 78 (312.00 B)

 Trainable params: 78 (312.00 B)

 Non-trainable params: 0 (0.00 B)

None
----------------------------------
[array([[ 4.3454516e-01,  3.8623810e-04,  3.8641548e-01,  2.1756738e-01,
         1.9726974e-01, -9.2450559e-02],
       [ 4.7095978e-01, -5.2342105e-01, -5.6376755e-02, -4.0506113e-01,
        -1.4233941e-01,  9.6414208e-02],
       [ 1.1934328e-01, -6.9420695e-02,  3.1314880e-01,  2.2722262e-01,
        -2.2284353e-01, -5.1254499e-01],
       [-1.7009360e-01, -4.8168996e-01,  3.0267698e-01,  2.8947586e-01,
         1.1504406e-01,  4.7266066e-02],
       [-5.6592429e-01,  9.9761367e-02, -5.1013172e-02,  1.7703491e-01,
        -2.2249320e-01, -2.3154485e-01],
       [ 1.5069693e-01,  2.8530061e-01,  3.9027601e-01,  2.1974128e-01,
        -1.8242630e-01,  3.6254239e-01],
       [-4.2048025e-01, -1.5200061e-01,  5.4168630e-01,  7.9769433e-02,
         4.0253043e-02, -4.5953640e-01],
       [ 4.2736578e-01,  4.3338859e-01, -5.1132500e-01,  5.6366539e-01,
        -3.1206948e-01,  2.9738748e-01],
       [-2.2893003e-01,  4.8307955e-02, -4.8631132e-02,

### Adding second hidden layer

In [22]:
ann.add(layers.Dense(units=6,activation="relu", name="deepLayer-2"))

In [23]:
displayNeuralNetwork(ann)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ deepLayer-1 (Dense)             │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ deepLayer-2 (Dense)             │ (None, 6)              │            42 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120 (480.00 B)

 Trainable params: 120 (480.00 B)

 Non-trainable params: 0 (0.00 B)

None
----------------------------------
[array([[ 4.3454516e-01,  3.8623810e-04,  3.8641548e-01,  2.1756738e-01,
         1.9726974e-01, -9.2450559e-02],
       [ 4.7095978e-01, -5.2342105e-01, -5.6376755e-02, -4.0506113e-01,
        -1.4233941e-01,  9.6414208e-02],
       [ 1.1934328e-01, -6.9420695e-02,  3.1314880e-01,  2.2722262e-01,
        -2.2284353e-01, -5.1254499e-01],
       [-1.7009360e-01, -4.8168996e-01,  3.0267698e-01,  2.8947586e-01,
         1.1504406e-01,  4.7266066e-02],
       [-5.6592429e-01,  9.9761367e-02, -5.1013172e-02,  1.7703491e-01,
        -2.2249320e-01, -2.3154485e-01],
       [ 1.5069693e-01,  2.8530061e-01,  3.9027601e-01,  2.1974128e-01,
        -1.8242630e-01,  3.6254239e-01],
       [-4.2048025e-01, -1.5200061e-01,  5.4168630e-01,  7.9769433e-02,
         4.0253043e-02, -4.5953640e-01],
       [ 4.2736578e-01,  4.3338859e-01, -5.1132500e-01,  5.6366539e-01,
        -3.1206948e-01,  2.9738748e-01],
       [-2.2893003e-01,  4.8307955e-02, -4.8631132e-02,

### Adding output layer

In [24]:
ann.add(layers.Dense(units=1,activation="sigmoid", name="output_layer"))

In [25]:
displayNeuralNetwork(ann)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ deepLayer-1 (Dense)             │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ deepLayer-2 (Dense)             │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 127 (508.00 B)

 Trainable params: 127 (508.00 B)

 Non-trainable params: 0 (0.00 B)

None
----------------------------------
[array([[ 4.3454516e-01,  3.8623810e-04,  3.8641548e-01,  2.1756738e-01,
         1.9726974e-01, -9.2450559e-02],
       [ 4.7095978e-01, -5.2342105e-01, -5.6376755e-02, -4.0506113e-01,
        -1.4233941e-01,  9.6414208e-02],
       [ 1.1934328e-01, -6.9420695e-02,  3.1314880e-01,  2.2722262e-01,
        -2.2284353e-01, -5.1254499e-01],
       [-1.7009360e-01, -4.8168996e-01,  3.0267698e-01,  2.8947586e-01,
         1.1504406e-01,  4.7266066e-02],
       [-5.6592429e-01,  9.9761367e-02, -5.1013172e-02,  1.7703491e-01,
        -2.2249320e-01, -2.3154485e-01],
       [ 1.5069693e-01,  2.8530061e-01,  3.9027601e-01,  2.1974128e-01,
        -1.8242630e-01,  3.6254239e-01],
       [-4.2048025e-01, -1.5200061e-01,  5.4168630e-01,  7.9769433e-02,
         4.0253043e-02, -4.5953640e-01],
       [ 4.2736578e-01,  4.3338859e-01, -5.1132500e-01,  5.6366539e-01,
        -3.1206948e-01,  2.9738748e-01],
       [-2.2893003e-01,  4.8307955e-02, -4.8631132e-02,

## Training ANN

### Compiline ANN

In [26]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training ANN

In [27]:
ann.fit(
    x_train,
    y_train,
    batch_size=32,
    epochs=25
)

Epoch 1/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7960 - loss: 0.5717
Epoch 2/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7960 - loss: 0.4967
Epoch 3/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7960 - loss: 0.4670
Epoch 4/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7975 - loss: 0.4454
Epoch 5/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8079 - loss: 0.4300
Epoch 6/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4219
Epoch 7/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8229 - loss: 0.4176
Epoch 8/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8266 - loss: 0.4143
Epoch 9/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8288 - loss: 0.4119
Epoch 10/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8280 - loss: 0.4099
Epoch 11/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8303 - loss: 0.4079
Epoch 12/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [28]:
displayNeuralNetwork(ann)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ deepLayer-1 (Dense)             │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ deepLayer-2 (Dense)             │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 383 (1.50 KB)

 Trainable params: 127 (508.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 256 (1.00 KB)

None
----------------------------------
[array([[ 0.32065737,  0.11095186,  0.26184815,  0.12435569, -0.03649354,
        -0.18068694],
       [ 0.544884  , -0.69662225, -0.09381068, -0.21892682,  0.03000018,
         0.1552283 ],
       [ 0.17312561, -0.01956953,  0.5016433 ,  0.21722053, -0.11913572,
        -0.46896806],
       [-0.05390494, -0.0495943 , -0.00345501,  0.27028894,  0.02877154,
        -0.013974  ],
       [-0.03453076,  0.08662891,  0.29084527,  0.3652747 ,  0.03990935,
        -0.2511638 ],
       [-0.09022546, -0.4046369 ,  0.3768242 , -0.762632  , -0.6633242 ,
         0.5763529 ],
       [-0.08236939,  0.00818689,  0.45467842,  0.07293034, -0.02706616,
        -0.49873355],
       [-0.46347764,  0.11051613, -0.62633955,  0.31986576, -0.16918625,
         0.1605085 ],
       [-1.1569504 , -0.15807576, -0.09922498, -0.17124419, -0.22753902,
        -0.3352835 ],
       [-0.06785381, -0.14719799,  0.20693868,  0.43541816, -0.01983492,
        -0.13842101],
       [-

## Making Predictions and evaluating model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [29]:
input_data = [[600,'France','Male',40,2,60000,2,1,1,50000]]

#### prepprocessing input data

In [30]:
inputDF = pd.DataFrame(input_data)
input=inputDF.values


In [31]:
input[:,2]= le.transform(input[:,2])

In [32]:
input

array([[600, 'France', 1, 40, 2, 60000, 2, 1, 1, 50000]], dtype=object)

In [33]:
input=ct.transform(input)

In [34]:
input

array([[1.0, 0.0, 0.0, 600, 1, 40, 2, 60000, 2, 1, 1, 50000]],
      dtype=object)

In [35]:
input=scaler.transform(input)

In [36]:
prediction=ann.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


In [37]:
prediction

array([[0.10890201]], dtype=float32)

prediction that the customer will leave is 0.038. Thus he will stay.

### Predicting Test Set

In [38]:
y_pred=ann.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [39]:
y_pred

array([[0.30848566],
       [0.36881512],
       [0.18876691],
       ...,
       [0.1680533 ],
       [0.2672121 ],
       [0.21859837]], dtype=float32)

In [40]:
y_pred=(y_pred>0.5)

In [41]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[1508,   87],
       [ 216,  189]])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.8485